/**
 * Tax Authority Sync Queue Service
 * 
 * Supports offline invoicing with deferred tax authority submission
 * 
 * Tax Authorities:
 * - TIMS (Kenya - Tax Invoice Management System)
 * - EFRIS (Uganda - Electronic Fiscal Receipting and Invoicing Solution)
 * - VFD (Tanzania - Virtual Fiscal Device)
 * - EBM (Rwanda - Electronic Billing Machine)
 */

import { TaxSyncQueue, Invoice, Transaction } from '@/types';
import { logTaxSync } from './audit.service';

const QUEUE_KEY = 'tax_sync_queue';
const MAX_RETRIES = 5;

/**
 * Add invoice to tax sync queue
 */
export function queueInvoiceSync(
  invoice: Invoice,
  authority: TaxSyncQueue['authority']
): TaxSyncQueue {
  const queueItem: TaxSyncQueue = {
    id: crypto.randomUUID(),
    entityType: 'invoice',
    entityId: invoice.id,
    payload: buildInvoicePayload(invoice, authority),
    authority,
    status: 'pending',
    retries: 0,
    createdAt: new Date().toISOString(),
  };
  
  saveToQueue(queueItem);
  
  console.log(`Queued invoice ${invoice.invoiceNumber} for sync to ${authority}`);
  
  return queueItem;
}

/**
 * Add transaction to tax sync queue
 */
export function queueTransactionSync(
  transaction: Transaction,
  authority: TaxSyncQueue['authority']
): TaxSyncQueue {
  const queueItem: TaxSyncQueue = {
    id: crypto.randomUUID(),
    entityType: 'transaction',
    entityId: transaction.id,
    payload: buildTransactionPayload(transaction, authority),
    authority,
    status: 'pending',
    retries: 0,
    createdAt: new Date().toISOString(),
  };
  
  saveToQueue(queueItem);
  
  return queueItem;
}

/**
 * Build invoice payload for specific tax authority
 */
function buildInvoicePayload(
  invoice: Invoice,
  authority: TaxSyncQueue['authority']
): any {
  // Base payload (common fields)
  const basePayload = {
    invoiceNumber: invoice.invoiceNumber,
    issueDate: invoice.issueDate,
    customerName: invoice.customerName,
    customerTaxId: invoice.customerTaxId,
    currency: invoice.currency,
    subtotal: invoice.subtotal,
    vatRate: invoice.vatRate,
    vatAmount: invoice.vatAmount,
    totalAmount: invoice.totalAmount,
    items: invoice.items,
  };
  
  // Authority-specific payloads
  switch (authority) {
    case 'TIMS': // Kenya
      return {
        ...basePayload,
        invoiceType: 'TAX_INVOICE',
        pinNumber: invoice.customerTaxId,
        deviceNumber: 'DEV001', // From device registration
      };
      
    case 'EFRIS': // Uganda
      return {
        ...basePayload,
        invoiceKind: '1', // Normal invoice
        buyerTin: invoice.customerTaxId,
        buyerLegalName: invoice.customerName,
        goodsDetails: invoice.items.map(item => ({
          item: item.description,
          qty: item.quantity,
          unitPrice: item.unitPrice,
          total: item.lineTotal,
          taxRate: invoice.vatRate,
        })),
      };
      
    case 'VFD': // Tanzania
      return {
        ...basePayload,
        vfdSerialNumber: 'VFD123456', // From VFD device
        receiptType: 'NORMAL',
        customerVrn: invoice.customerTaxId,
      };
      
    case 'EBM': // Rwanda
      return {
        ...basePayload,
        sdcId: 'SDC001', // Sales Data Controller ID
        invoiceSignature: '', // Will be generated by EBM
      };
      
    default:
      return basePayload;
  }
}

/**
 * Build transaction payload for tax authority
 */
function buildTransactionPayload(
  transaction: Transaction,
  authority: TaxSyncQueue['authority']
): any {
  return {
    transactionId: transaction.id,
    date: transaction.date,
    type: transaction.type,
    amount: transaction.amount,
    vatRate: transaction.vatRate,
    vatAmount: transaction.vatAmount,
    totalAmount: transaction.totalAmount,
    description: transaction.description,
    reference: transaction.reference,
  };
}

/**
 * Process sync queue
 */
export async function processSyncQueue(apiUrl: string = 'http://localhost:3000'): Promise<{
  processed: number;
  succeeded: number;
  failed: number;
  errors: string[];
}> {
  const queue = getQueue();
  const pending = queue.filter(item => item.status === 'pending');
  
  if (pending.length === 0) {
    return { processed: 0, succeeded: 0, failed: 0, errors: [] };
  }
  
  console.log(`Processing ${pending.length} pending tax sync items...`);
  
  let succeeded = 0;
  let failed = 0;
  const errors: string[] = [];
  
  for (const item of pending) {
    try {
      await syncToAuthority(item, apiUrl);
      markSynced(item.id);
      succeeded++;
      
      // Log audit
      logTaxSync(item.entityType, item.entityId, item.authority, 'success', 'system');
    } catch (error: any) {
      failed++;
      errors.push(`${item.authority} sync failed for ${item.entityId}: ${error.message}`);
      
      // Increment retries
      const retries = incrementRetries(item.id);
      
      if (retries >= MAX_RETRIES) {
        markFailed(item.id, error.message);
        logTaxSync(item.entityType, item.entityId, item.authority, 'failed', 'system');
      }
    }
  }
  
  return {
    processed: pending.length,
    succeeded,
    failed,
    errors,
  };
}

/**
 * Sync item to tax authority
 */
async function syncToAuthority(
  item: TaxSyncQueue,
  apiUrl: string
): Promise<void> {
  const endpoint = `${apiUrl}/api/v1/tax-sync/${item.authority.toLowerCase()}`;
  
  const response = await fetch(endpoint, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(item.payload),
  });
  
  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText}`);
  }
  
  const result = await response.json();
  
  // Update entity with compliance data
  if (item.entityType === 'invoice') {
    updateInvoiceComplianceData(item.entityId, item.authority, result);
  }
}

/**
 * Update invoice with compliance data from tax authority
 */
function updateInvoiceComplianceData(
  invoiceId: string,
  authority: TaxSyncQueue['authority'],
  responseData: any
): void {
  const invoices = JSON.parse(localStorage.getItem('invoices') || '[]');
  const invoice = invoices.find((inv: Invoice) => inv.id === invoiceId);
  
  if (!invoice) return;
  
  invoice.complianceData = invoice.complianceData || {};
  
  switch (authority) {
    case 'TIMS':
      invoice.complianceData.timsInvoiceId = responseData.invoiceId;
      invoice.complianceData.timsQrCode = responseData.qrCode;
      invoice.complianceData.verificationUrl = responseData.verificationUrl;
      break;
      
    case 'EFRIS':
      invoice.complianceData.efrisInvoiceId = responseData.invoiceId;
      invoice.complianceData.efrisFdmSignature = responseData.signature;
      break;
      
    case 'VFD':
      invoice.complianceData.vfdReceiptNumber = responseData.receiptNumber;
      invoice.complianceData.vfdVerificationCode = responseData.verificationCode;
      break;
      
    case 'EBM':
      invoice.complianceData.ebmInvoiceId = responseData.invoiceId;
      invoice.complianceData.ebmSdcId = responseData.sdcId;
      break;
  }
  
  invoice.taxSyncStatus = 'synced';
  invoice.taxSyncedAt = new Date().toISOString();
  
  localStorage.setItem('invoices', JSON.stringify(invoices));
}

/**
 * Mark item as synced
 */
function markSynced(itemId: string): void {
  const queue = getQueue();
  const item = queue.find(i => i.id === itemId);
  
  if (item) {
    item.status = 'synced';
    item.syncedAt = new Date().toISOString();
    saveQueue(queue);
  }
}

/**
 * Mark item as failed
 */
function markFailed(itemId: string, errorMessage: string): void {
  const queue = getQueue();
  const item = queue.find(i => i.id === itemId);
  
  if (item) {
    item.status = 'failed';
    item.errorMessage = errorMessage;
    saveQueue(queue);
  }
}

/**
 * Increment retry count
 */
function incrementRetries(itemId: string): number {
  const queue = getQueue();
  const item = queue.find(i => i.id === itemId);
  
  if (item) {
    item.retries++;
    item.lastAttempt = new Date().toISOString();
    saveQueue(queue);
    return item.retries;
  }
  
  return 0;
}

/**
 * Get sync queue
 */
function getQueue(): TaxSyncQueue[] {
  const stored = localStorage.getItem(QUEUE_KEY);
  return stored ? JSON.parse(stored) : [];
}

/**
 * Save to queue
 */
function saveToQueue(item: TaxSyncQueue): void {
  const queue = getQueue();
  queue.push(item);
  saveQueue(queue);
}

/**
 * Save queue
 */
function saveQueue(queue: TaxSyncQueue[]): void {
  localStorage.setItem(QUEUE_KEY, JSON.stringify(queue));
}

/**
 * Get queue summary
 */
export function getQueueSummary(): {
  pending: number;
  synced: number;
  failed: number;
  byAuthority: Record<string, number>;
} {
  const queue = getQueue();
  
  const summary = {
    pending: queue.filter(i => i.status === 'pending').length,
    synced: queue.filter(i => i.status === 'synced').length,
    failed: queue.filter(i => i.status === 'failed').length,
    byAuthority: {} as Record<string, number>,
  };
  
  queue.forEach(item => {
    summary.byAuthority[item.authority] = (summary.byAuthority[item.authority] || 0) + 1;
  });
  
  return summary;
}

/**
 * Get failed items for retry
 */
export function getFailedItems(): TaxSyncQueue[] {
  return getQueue().filter(i => i.status === 'failed');
}

/**
 * Retry failed item
 */
export async function retryFailedItem(itemId: string, apiUrl?: string): Promise<void> {
  const queue = getQueue();
  const item = queue.find(i => i.id === itemId);
  
  if (!item || item.status !== 'failed') {
    throw new Error('Item not found or not in failed state');
  }
  
  // Reset status and retry
  item.status = 'pending';
  item.retries = 0;
  item.errorMessage = undefined;
  saveQueue(queue);
  
  // Process immediately
  await processSyncQueue(apiUrl);
}

/**
 * Clear synced items from queue (cleanup)
 */
export function clearSyncedItems(): number {
  const queue = getQueue();
  const pending = queue.filter(i => i.status !== 'synced');
  const removed = queue.length - pending.length;
  
  saveQueue(pending);
  
  return removed;
}

/**
 * Auto-sync worker (call this on app init)
 */
export function initTaxSyncWorker(apiUrl?: string): void {
  // Initial sync on load
  if (navigator.onLine) {
    processSyncQueue(apiUrl).catch(console.error);
  }
  
  // Sync when network reconnects
  window.addEventListener('online', () => {
    console.log('Network reconnected, syncing tax data...');
    processSyncQueue(apiUrl).catch(console.error);
  });
  
  // Periodic sync (every 10 minutes)
  setInterval(() => {
    if (navigator.onLine) {
      processSyncQueue(apiUrl).catch(console.error);
    }
  }, 10 * 60 * 1000);
}
