/**
 * Electron Main Process
 * Enterprise Installer for EA Accounting Platform
 */

const { app, BrowserWindow, ipcMain, dialog } = require('electron');
const path = require('path');
const fs = require('fs').promises;
const { execSync, spawn } = require('child_process');
const jwt = require('jsonwebtoken');
const Docker = require('dockerode');

const docker = new Docker();
let mainWindow;

// Create main window
function createWindow() {
  mainWindow = new BrowserWindow({
    width: 900,
    height: 700,
    minWidth: 800,
    minHeight: 600,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      preload: path.join(__dirname, 'preload.js')
    },
    autoHideMenuBar: true,
    icon: path.join(__dirname, '../assets/icon.png')
  });

  // Load React app
  if (process.env.NODE_ENV === 'development') {
    mainWindow.loadURL('http://localhost:5173');
    mainWindow.webContents.openDevTools();
  } else {
    mainWindow.loadFile(path.join(__dirname, '../build/index.html'));
  }
}

app.whenReady().then(createWindow);

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// ========================================
// LICENSE VALIDATION
// ========================================

ipcMain.handle('validate-license', async (event, licenseKey) => {
  try {
    // In production, this calls your license server
    // For now, decode and validate JWT structure
    
    const decoded = jwt.decode(licenseKey);
    
    if (!decoded) {
      return { valid: false, error: 'Invalid license format' };
    }

    // Validate expiry
    const now = Math.floor(Date.now() / 1000);
    if (decoded.exp && decoded.exp < now) {
      return { valid: false, error: 'License expired' };
    }

    // Validate issuer
    if (decoded.iss !== 'eastbooks.com') {
      return { valid: false, error: 'Invalid license issuer' };
    }

    return {
      valid: true,
      license: {
        plan: decoded.plan,
        deployment: decoded.deployment,
        users: decoded.users,
        modules: decoded.modules,
        expires: new Date(decoded.exp * 1000).toISOString().split('T')[0],
        support: decoded.support
      }
    };
  } catch (error) {
    return { valid: false, error: error.message };
  }
});

// ========================================
// ENVIRONMENT GENERATION
// ========================================

ipcMain.handle('generate-env', async (event, config) => {
  try {
    const envContent = `# EA Accounting Platform Configuration
# Generated by installer on ${new Date().toISOString()}

# Deployment
DEPLOYMENT_TYPE=${config.deployment}
NODE_ENV=production

# Country & Compliance
COUNTRY_CODE=${config.country}
TAX_SYSTEM=${config.taxSystem}
VAT_RATE=${config.vatRate}

# Database
DB_HOST=localhost
DB_PORT=5432
DB_NAME=eastbooks_${config.deployment}
DB_USER=eastbooks
DB_PASSWORD=${generatePassword()}

# Server
PORT=3000
API_PORT=5000

# JWT
JWT_SECRET=${generateSecret(64)}
JWT_REFRESH_SECRET=${generateSecret(64)}

# License
LICENSE_KEY=${config.licenseKey}
MODULES=${config.modules.join(',')}
MAX_USERS=${config.maxUsers}

# Tax Authority Device IDs (configure after installation)
${config.country === 'KE' ? 'TIMS_DEVICE_SERIAL=' : ''}
${config.country === 'UG' ? 'EFRIS_DEVICE_ID=' : ''}
${config.country === 'TZ' ? 'VFD_SERIAL=' : ''}
${config.country === 'RW' ? 'EBM_SERIAL=\nSDC_ID=' : ''}

# Features
ENABLE_PAYROLL=${config.modules.includes('payroll')}
ENABLE_INVENTORY=${config.modules.includes('inventory')}

# Logs
LOG_LEVEL=info
LOG_FILE=./logs/app.log
`;

    const installPath = getInstallPath(config.deployment);
    await fs.mkdir(installPath, { recursive: true });
    await fs.writeFile(path.join(installPath, '.env'), envContent);

    return { success: true, path: installPath };
  } catch (error) {
    return { success: false, error: error.message };
  }
});

// ========================================
// DOCKER COMPOSE GENERATION
// ========================================

ipcMain.handle('generate-docker-compose', async (event, config) => {
  try {
    let composeTemplate;

    switch (config.deployment) {
      case 'on-premise':
        composeTemplate = getOnPremiseCompose(config);
        break;
      case 'private':
        composeTemplate = getPrivateCloudCompose(config);
        break;
      case 'cloud':
        composeTemplate = getCloudCompose(config);
        break;
      default:
        throw new Error('Invalid deployment type');
    }

    const installPath = getInstallPath(config.deployment);
    await fs.writeFile(
      path.join(installPath, 'docker-compose.yml'),
      composeTemplate
    );

    return { success: true, path: installPath };
  } catch (error) {
    return { success: false, error: error.message };
  }
});

// ========================================
// DOCKER DEPLOYMENT
// ========================================

ipcMain.handle('check-docker', async () => {
  try {
    await docker.ping();
    const info = await docker.info();
    return { 
      installed: true, 
      version: info.ServerVersion,
      running: true 
    };
  } catch (error) {
    return { 
      installed: false, 
      error: 'Docker is not installed or not running' 
    };
  }
});

ipcMain.handle('deploy-docker', async (event, config) => {
  try {
    const installPath = getInstallPath(config.deployment);
    
    // Send progress updates
    const sendProgress = (step, status, message) => {
      event.sender.send('install-progress', { step, status, message });
    };

    // Step 1: Pull images
    sendProgress('pull', 'running', 'Pulling Docker images...');
    await pullDockerImages(sendProgress);

    // Step 2: Create network
    sendProgress('network', 'running', 'Creating Docker network...');
    await createDockerNetwork('eastbooks-network');

    // Step 3: Start services
    sendProgress('services', 'running', 'Starting services...');
    await startDockerCompose(installPath, sendProgress);

    // Step 4: Wait for health checks
    sendProgress('health', 'running', 'Waiting for services to be healthy...');
    await waitForHealthy(config);

    // Step 5: Run database migrations
    sendProgress('migrate', 'running', 'Running database migrations...');
    await runMigrations(installPath);

    // Step 6: Seed initial data
    if (config.seedData) {
      sendProgress('seed', 'running', 'Seeding initial data...');
      await seedDatabase(installPath, config);
    }

    sendProgress('complete', 'success', 'Installation complete!');

    return { 
      success: true, 
      url: `http://localhost:${config.port || 3000}`,
      credentials: {
        email: 'admin@yourcompany.com',
        password: 'Check your email'
      }
    };
  } catch (error) {
    event.sender.send('install-progress', { 
      step: 'error', 
      status: 'error', 
      message: error.message 
    });
    return { success: false, error: error.message };
  }
});

// ========================================
// HELPER FUNCTIONS
// ========================================

function getInstallPath(deployment) {
  const homedir = require('os').homedir();
  
  switch (deployment) {
    case 'on-premise':
      return path.join(homedir, 'EastBooks');
    case 'private':
      return path.join(homedir, 'EastBooks-Private');
    case 'cloud':
      return path.join(homedir, '.eastbooks');
    default:
      return path.join(homedir, 'EastBooks');
  }
}

function generatePassword(length = 32) {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*';
  let password = '';
  for (let i = 0; i < length; i++) {
    password += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return password;
}

function generateSecret(length = 64) {
  return require('crypto').randomBytes(length).toString('hex');
}

function getOnPremiseCompose(config) {
  return `version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: eastbooks-db
    environment:
      POSTGRES_DB: eastbooks_${config.deployment}
      POSTGRES_USER: eastbooks
      POSTGRES_PASSWORD: \${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - eastbooks-network
    restart: unless-stopped

  backend:
    image: eastbooks/backend:latest
    container_name: eastbooks-api
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=eastbooks_${config.deployment}
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - eastbooks-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: eastbooks/frontend:latest
    container_name: eastbooks-web
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - eastbooks-network
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  eastbooks-network:
    driver: bridge
`;
}

function getPrivateCloudCompose(config) {
  // Similar to on-premise but with external network and monitoring
  return getOnPremiseCompose(config) + `
  redis:
    image: redis:7-alpine
    container_name: eastbooks-cache
    networks:
      - eastbooks-network
    restart: unless-stopped
`;
}

function getCloudCompose(config) {
  // Minimal compose for cloud-managed database
  return getOnPremiseCompose(config);
}

async function pullDockerImages(sendProgress) {
  const images = [
    'postgres:15-alpine',
    'eastbooks/backend:latest',
    'eastbooks/frontend:latest'
  ];

  for (const image of images) {
    sendProgress('pull', 'running', `Pulling ${image}...`);
    
    await new Promise((resolve, reject) => {
      docker.pull(image, (err, stream) => {
        if (err) return reject(err);
        
        docker.modem.followProgress(stream, (err, output) => {
          if (err) return reject(err);
          resolve(output);
        });
      });
    });
  }
}

async function createDockerNetwork(name) {
  try {
    const networks = await docker.listNetworks();
    const exists = networks.find(n => n.Name === name);
    
    if (!exists) {
      await docker.createNetwork({ Name: name });
    }
  } catch (error) {
    console.error('Network creation error:', error);
  }
}

async function startDockerCompose(installPath, sendProgress) {
  return new Promise((resolve, reject) => {
    const process = spawn('docker-compose', ['up', '-d'], {
      cwd: installPath,
      stdio: ['ignore', 'pipe', 'pipe']
    });

    process.stdout.on('data', (data) => {
      sendProgress('services', 'running', data.toString().trim());
    });

    process.stderr.on('data', (data) => {
      sendProgress('services', 'running', data.toString().trim());
    });

    process.on('close', (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`Docker Compose failed with code ${code}`));
      }
    });
  });
}

async function waitForHealthy(config, timeout = 120000) {
  const startTime = Date.now();
  const checkInterval = 5000;

  while (Date.now() - startTime < timeout) {
    try {
      const response = await fetch(`http://localhost:${config.port || 3000}/api/health`);
      if (response.ok) {
        return true;
      }
    } catch (error) {
      // Service not ready yet
    }
    
    await new Promise(resolve => setTimeout(resolve, checkInterval));
  }

  throw new Error('Services failed to become healthy');
}

async function runMigrations(installPath) {
  return new Promise((resolve, reject) => {
    const process = spawn('docker-compose', ['exec', '-T', 'backend', 'npm', 'run', 'migrate'], {
      cwd: installPath
    });

    process.on('close', (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error('Database migration failed'));
      }
    });
  });
}

async function seedDatabase(installPath, config) {
  return new Promise((resolve, reject) => {
    const process = spawn('docker-compose', ['exec', '-T', 'backend', 'npm', 'run', 'seed'], {
      cwd: installPath
    });

    process.on('close', (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error('Database seeding failed'));
      }
    });
  });
}

// ========================================
// SELECT INSTALL DIRECTORY
// ========================================

ipcMain.handle('select-directory', async () => {
  const result = await dialog.showOpenDialog(mainWindow, {
    properties: ['openDirectory', 'createDirectory']
  });

  if (!result.canceled && result.filePaths.length > 0) {
    return { success: true, path: result.filePaths[0] };
  }

  return { success: false };
});
